default:
  tags: [linux,docker]
  image: registry.gitlab.com/libtiff/libtiff-ci-ubuntu24.04:latest

stages:
  - build

# Only Cygwin jobs enabled for debugging test_directory segfault

windows-cygwin-release:
  stage: build
  tags: [windows, docker]
  image: registry.gitlab.com/codelibre/containers/cygwin-libtiff:latest
  script:
    - bash build/gitlab-ci-cygwin Ninja Release

windows-cygwin-debug:
  stage: build
  tags: [windows, docker]
  image: registry.gitlab.com/codelibre/containers/cygwin-libtiff:latest
  script:
    - bash build/gitlab-ci-cygwin Ninja Debug
